# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0b\x41\x64\x64Response\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32.\n\nCalculator\x12 \n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDREQUEST']._serialized_start=20
  _globals['_ADDREQUEST']._serialized_end=54
  _globals['_ADDRESPONSE']._serialized_start=56
  _globals['_ADDRESPONSE']._serialized_end=82
  _globals['_CALCULATOR']._serialized_start=84
  _globals['_CALCULATOR']._serialized_end=130
# @@protoc_insertion_point(module_scope)
